### ISSUE TITLE
nuget packages

### ISSUE THREAD

**Issue by Marijn17s** [Disc0rdTools/NitroSniper#1]
May i ask which nuget packages you used? Currently getting quite a few errors when trying to build it

(main issue is with the TokenType as i can only choose Bearer, Bot, Webhook. But you have User. so i'm wondering how that works?

**Comment by Disc0rdTools** [comment]
Hi, it's normal that you encounter this problem if you used the classic version of discord.NET, which no longer supports user tokens since version 2. So I used Discord.Net-Anarchy, which support sthem (I deliberately didn't put the package files so that skids wouldn't be able to change the code and resell it, even though it's basically open source...).
